name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project files to Azure VM
        run: |
          rsync -avz --exclude='.git' --exclude='.github' --exclude='README.md' ./ azureuser@20.224.160.150:~/animatch/

      - name: Restart Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.224.160.150 << 'EOF'
          cd ~/animatch
          docker compose down
          docker compose up -d --build
          docker exec animatch-web chown -R www-data:www-data /var/www/html
          EOF
